services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kairos_admin
      POSTGRES_PASSWORD: kairos_password
      POSTGRES_DB: kairos_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"